### ISSUE TITLE
Will Visual Studio be supported?

### ISSUE THREAD

**Issue by KevinZonda** [ZenUml/jetbrains-zenuml#114]
Have plan or....

**Comment by MrCoder** [comment]
Hi @KevinZonda , we do not really have a plan to support Visual Studio. We do have an extension for VS Code (alpha though). https://marketplace.visualstudio.com/items?itemName=mrcoder.zenuml

Any interest to create one :)

**Comment by KevinZonda** [comment]
> Hi @KevinZonda , we do not really have a plan to support Visual Studio. We do have an extension for VS Code (alpha though). https://marketplace.visualstudio.com/items?itemName=mrcoder.zenuml
> 
> Any interest to create one :)

What's a pity! Anyway, thanks for providing such a convenient tool. Have a good day :)
